Individual reminders closes #3
turingschool-projects/1610-remember-6 pull request #8
Opened 2017-02-11 21:58 UTC by DanGrund

## Purpose

closes #3
When the user clicks on one of the reminders on the page, they are taken to an individual reminders route (ie: ‘/reminders/1’, if the id of the reminder is 1). The title of the reminder object should be displayed.

You’ll need a reminder route in addition to the reminders route.
It should be nested inside the reminders route.
The user should still see all of the reminders from your previous feature. The specific reminder they are looking at now should be rendered in the outlet of the reminders.hbs template.
There should be some CSS for the .active class.

## Approach

We created a nested route, then modified the router to link to the reminder:id when a reminder is selected. The index route displays reminder titles, and when a user clicks a title, the date and body of the reminder are displayed in the outlet. The class 'active' is automatically applied to a clicked link by ember (fancy af), so we just added a css magenta text-color to show that it is indeed active. 

### Test coverage 

The test you wrote has been modified to make a few additional asserts. we test for correct URL, correct, test, and for the class Active occuring. 

### Follow-up tasks

- [Issue #5 (Example)](https://github.com/turingschool-projects/1610-remember-6/issues/5)

### Screenshots

#### Before

![issue2-after](https://cloud.githubusercontent.com/assets/20474299/22857815/23e66854-f06a-11e6-839e-3dcb8c7523ab.png)

#### After

<img width="942" alt="issue-3-after" src="https://cloud.githubusercontent.com/assets/20474299/22857825/713f4a30-f06a-11e6-86f2-c4d22f13bfdc.png">

#### Tests

<img width="431" alt="issue-3-tests" src="https://cloud.githubusercontent.com/assets/20474299/22857828/7c092922-f06a-11e6-93bf-6a7500159c3d.png">

2017-02-11 22:53 UTC, martensonbj requested changes
Would love to hear about what's going on in your router.js file

2017-02-11 22:53 UTC, martensonbj commented on app/router.js
> +  this.route('/');
What's going on with this guy? Are you using the index route for something in particular?

2017-02-11 22:53 UTC, martensonbj commented on app/router.js
> +    this.route('index', { path: '/' });
Not sure you need this either. Talk to me a little bit about what your routing situation is.

2017-02-11 23:04 UTC, DanGrund commented on app/router.js
> +  this.route('/');
Honestly just didn't realize they weren't necessary anymore. removing now.

2017-02-11 23:04 UTC, DanGrund commented on app/router.js
> +    this.route('index', { path: '/' });
see above

2017-02-11 23:07 UTC, DanGrund reviewed
Removed lines 11 & 13 from the router as they are unneccessary. Ember is full of fancy ass black magic and just automatically knows how to treat index routes without us explicitly defining them. wizardry.

2017-02-11 23:42 UTC, Tman22 commented on app/router.js
> +    this.route('reminder', { path: '/:id' });
Would you mind changing :id to :reminder_id -> Ember follows the convention of :model-name_id for two reasons. The first reason is that Routes know how to fetch the right model by default, if you follow the convention. The second is that params is an object, and can only have one value associated with a key. 
https://guides.emberjs.com/v2.11.0/routing/defining-your-routes/

2017-02-12 17:37 UTC, DanGrund reviewed
updated to :reminder_id

2017-02-13 00:43 UTC, martensonbj approved these changes

2017-02-13 00:43 UTC, merged